### ISSUE TITLE
Inconsistency in Data Format Instructions between README and R Script

### ISSUE THREAD

**Issue by Noamsarna** [craddm/metaSDT#4]
It appears there is a discrepancy between the data format instructions provided in the README file and the format used in the R script.

**Issue Description**:
In the README file, the suggested format for preparing data for the function is listed as:

A1, A2, A3, B3, B2, B1.

However, upon examining the R script (particularly in [this section](https://github.com/craddm/metaSDT/blob/dc8648a48ad13c776d13d447d32e1cfe61ab2e5a/R/sdt_functions.R#L219-L253)), I noticed that the data format is actually:

A3, A2, A1, B1, B2, B3.

**Impact**:
This inconsistency in data format instructions could lead to incorrect implementation of the function, ultimately affecting the resulting metacognitive SDT measures. 

**Suggested Resolution**:
Could you please clarify which format is the correct one? Additionally, updating either the README or the R script to ensure consistency would be greatly beneficial for future users.

Thank you for your attention to this matter. I appreciate the work you are doing with this library and look forward to your response.

**Comment by craddm** [comment]
Thanks for this - the readme is incorrect. The instructions in the help text are correct. I think I was writing it hurriedly and using the numbers to indicate levels without thinking through what those levels were supposed to mean (i.e. I was labelling _low_ as 3 in the readme, which is obviously confusing).
